# Generated by Django 5.0.6 on 2025-11-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_seller_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.AddField(
            model_name="productimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
